# Generated by Django 3.2.3 on 2021-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('level', models.CharField(max_length=24)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
    ]
